if(surface_exists(surf))surface_free(surf);
layer_sequence_destroy(plane_sequence)
layer_sequence_destroy(flame_upper_sequence)
layer_sequence_destroy(flame_lower_sequence)
instance_destroy(bullet_emitter_inst)