event_inherited();

idle_mode = EQUIPMENT_IDLE_MODE.SEQUENCE
idle_sequence = seq_plasma_cannon_b_idle
rampage_intro = seq_plasma_cannon_b_rampage_intro
rampage = seq_plasma_cannon_b_rampage
rampage_outro_mode = EQUIPMENT_RAMPAGE_OUTRO_MODE.REVERSE_INTRO
rampage_outro = seq_plasma_cannon_b_rampage_intro

bullet_emitter = emitter_wingman_plasma_cannon_b