live;
if(surface_exists(surf))surface_free(surf);
if(surface_exists(surf_effect))surface_free(surf_effect);
layer_sequence_destroy(enemy_sequence)
layer_sequence_destroy(flame_lower_sequence)
layer_sequence_destroy(flame_upper_sequence)
layer_destroy(layer_enemy)
layer_destroy(layer_enemy_lower)
layer_destroy(layer_enemy_upper)
instance_destroy(bullet_emitter_inst)
if(sprite_exists(mask_sprite))sprite_delete(mask_sprite);